auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /00_data/loki/
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory


query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

querier:
  query_timeout: 5m
  max_concurrent: 2048
  engine:
    timeout: 5m
analytics:
  reporting_enabled: false


schema_config:
  configs:
    - from: 2023-10-10
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: network_index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /00_data/loki/index
    cache_location: /00_data/loki/index_cache
    shared_store: aws
  aws:
    bucketnames: netflow-agg
    endpoint: aiopss3.cstcloud.cn
    access_key_id: 4bee9b5a927f11ee9c2fb4055d678c75
    secret_access_key: 911e3de735cc0e152c3dfdc471a07978cd84bc96
    http_config:
      insecure_skip_verify: true

compactor:
  working_directory: /00_data/loki/compactor
  shared_store: aws
  compaction_interval: 5m

limits_config:
  per_stream_rate_limit: 64MB
  ingestion_rate_mb: 256
