server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: netflow-agg-140
    static_configs:
      - targets:
          - 127.0.0.1
        labels:
          job: 5m
          __path__: /root/work/log/140/5m/**/*.log


